config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "customers#index"

  get "customers/alphabetized", to: "customers#alphabetized"

  get "customers/missing_email", to: "customers#missing_email"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @pageName = "All Customers - Displayed in Database Order"
    @customers = Customer.all
  end

  def alphabetized
    @pageName = "All Customers - Displayed in Alphabetical Order"
    @customers = Customer.order(:name)
    render :index
  end

  def missing_email
    @pageName = "Customers missing an email address"
    @customers = Customer.where(email: '')
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column is one-one-third">
  <div class="card">
    <div class="card-content">
      <h2 class="subtitle is-5"> <%= customer.name %> </h2>
      <div class="card-image">
        <figure class="image is-1by1">
          <% if customer.image.present? %>
            <%= image_tag customer.image %>
          <% end %>
        </figure>
      </div>
      <p><strong>Phone Number:</strong> <%= customer.phone %> </p>
      <p><strong>Email:</strong> <%= customer.email %> </p>

    </div>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h1><%= @pageName %></h1>

<%= render @customers %>

app/views/customers/index.html.erb
  <div class="columns is-multiline">
    <div class="container">
      <h1 class="title is-3"><%= @pageName %></h1>
    </div>
    <div class="container">
      <%= render @customers %>
    </div>
  </div>

app/views/customers/missing_email.html.erb
<h1><%= @pageName %></h1>

<%= render @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>CustomerRelationshipManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>
  </head>

    <nav class="navbar">
        <li class="navbar-item"><%= link_to 'Home', root_path %></li>
        <li class="navbar-item"><%= link_to 'Alphabetized', customers_alphabetized_path %></li>
        <li class="navbar-item"><%= link_to 'Missing Email', customers_missing_email_path %></li>
    </nav>

  <body>

    <section class="section">

      <div class="container">
        <h1 class="title is-1">Customer Relationship Manager</h1>
        <h2 class="subtitle is-3">Ultimate Challenge 6</h2>
        <br/>
      </div>

      <div class="container">
        <%= yield %>
      </div>

   </section>

  </body>

</html>